# Generated by Django 6.0 on 2026-01-13 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('type', models.CharField(choices=[('quality_classifier', 'Quality Classifier'), ('sentiment_analyzer', 'Sentiment Analyzer')], default='quality_classifier', max_length=50)),
                ('status', models.CharField(choices=[('training', 'Training'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=50)),
                ('accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('training_data_count', models.IntegerField(blank=True, null=True)),
                ('last_trained', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('questions', models.JSONField(default=list)),
                ('require_qualification', models.BooleanField(default=False)),
                ('qualification_pass_score', models.IntegerField(blank=True, null=True)),
                ('allowed_domains', models.JSONField(default=list)),
                ('design', models.JSONField(default=dict)),
                ('response_counter', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespondentQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_email', models.EmailField(max_length=254)),
                ('qualification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('questions', models.JSONField(default=list)),
                ('time_limit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_tests', to='surveys.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_email', models.EmailField(max_length=254)),
                ('responses', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quality_score', models.IntegerField(default=100)),
                ('quality_analysis', models.JSONField(default=dict)),
                ('is_flagged', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['user', '-created_at'], name='surveys_sur_user_id_4607f6_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'respondent_email'], name='surveys_sur_survey__160fab_idx'),
        ),
    ]
