# Generated by Django 6.0 on 2026-01-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIModel',
        ),
    ]
